# Generated by Django 6.0.2 on 2026-03-03 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view_profile', 'Viewed Profile'), ('send_request', 'Sent Request'), ('accept_request', 'Accepted Request'), ('reject_request', 'Rejected Request'), ('block_user', 'Blocked User'), ('report_user', 'Reported User')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='communicati_user_id_d6a628_idx')],
            },
        ),
    ]
