# Generated by Django 6.0.2 on 2026-10-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_savedprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('view_profile', 'Viewed Profile'), ('send_request', 'Sent Request'), ('accept_request', 'Accepted Request'), ('reject_request', 'Rejected Request'), ('block_user', 'Blocked User'), ('report_user', 'Reported User'), ('unmatch', 'Unmatched User')], max_length=50),
        ),
    ]
