# Generated by Django 6.0.2 on 2026-10-07 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_alter_activitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['receiver', 'status'], name='req_receiver_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['sender', 'status'], name='req_sender_status_idx'),
        ),
    ]
