# Generated by Django 6.0.2 on 2026-10-07 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('silver', 'Silver Plan'), ('gold', 'Gold Plan'), ('diamond', 'Diamond VIP Plan')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('features', models.TextField(help_text='Newline-separated list of features')),
                ('badge_label', models.CharField(blank=True, help_text='e.g. Most Popular, Best Value', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('utr_number', models.CharField(blank=True, help_text='12-digit UPI Transaction / UTR Number', max_length=50, null=True)),
                ('payment_method', models.CharField(default='UPI QR', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('completed', 'Verified & Active'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
