# Generated by Django 6.0.2 on 2026-10-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('completed', 'Active'), ('superseded', 'Superseded'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
