# Generated by Django 6.0.2 on 2026-10-07 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.UniqueConstraint(condition=models.Q(('utr_number__isnull', False), models.Q(('status', 'rejected'), _negated=True)), fields=('utr_number',), name='unique_active_utr_order'),
        ),
    ]
