# Generated by Django 6.0.2 on 2026-02-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='height_feet',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='e.g. 5.8', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, help_text='e.g. Software Engineer, Farmer', max_length=100),
        ),
    ]
