# Generated by Django 6.0.3 on 2026-03-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_email_verified_and_more'),
    ]

    operations = [
    migrations.AddField(
        model_name='customuser',
        name='is_email_verified',
        field=models.BooleanField(default=False),
    ),
]
