# Generated by Django 6.0.2 on 2026-10-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='caste',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caste / Community'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sub_caste',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sub-Caste / Gotra'),
        ),
    ]
