# Generated by Django 6.0.2 on 2026-10-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0010_verify_existing_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'is_approved', 'is_suspended', 'gender'], name='user_match_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['city', 'gender'], name='user_city_gender_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['caste', 'gender'], name='user_caste_gender_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['-date_joined'], name='user_date_joined_idx'),
        ),
    ]
