# Generated by Django 6.0.2 on 2026-03-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='height_feet',
        ),
        migrations.AddField(
            model_name='customuser',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
